// Code generated by MockGen. DO NOT EDIT.
// Source: internal/gophermart/presentation/factory/usecase_factory.go
//
// Generated by this command:
//
//	mockgen -source=internal/gophermart/presentation/factory/usecase_factory.go -destination=internal/gophermart/presentation/factory/mocks/mock_usecase_factory.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	dto "gophermart/internal/gophermart/application/dto"
	port "gophermart/internal/gophermart/application/port"
	vo "gophermart/internal/gophermart/domain/vo"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUseCaseFactory is a mock of UseCaseFactory interface.
type MockUseCaseFactory struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseFactoryMockRecorder
	isgomock struct{}
}

// MockUseCaseFactoryMockRecorder is the mock recorder for MockUseCaseFactory.
type MockUseCaseFactoryMockRecorder struct {
	mock *MockUseCaseFactory
}

// NewMockUseCaseFactory creates a new mock instance.
func NewMockUseCaseFactory(ctrl *gomock.Controller) *MockUseCaseFactory {
	mock := &MockUseCaseFactory{ctrl: ctrl}
	mock.recorder = &MockUseCaseFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUseCaseFactory) EXPECT() *MockUseCaseFactoryMockRecorder {
	return m.recorder
}

// GetBalanceUseCase mocks base method.
func (m *MockUseCaseFactory) GetBalanceUseCase() port.UseCase[vo.UserID, dto.BalanceOutput] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalanceUseCase")
	ret0, _ := ret[0].(port.UseCase[vo.UserID, dto.BalanceOutput])
	return ret0
}

// GetBalanceUseCase indicates an expected call of GetBalanceUseCase.
func (mr *MockUseCaseFactoryMockRecorder) GetBalanceUseCase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalanceUseCase", reflect.TypeOf((*MockUseCaseFactory)(nil).GetBalanceUseCase))
}

// ListOrdersUseCase mocks base method.
func (m *MockUseCaseFactory) ListOrdersUseCase() port.UseCase[vo.UserID, []dto.OrderOutput] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrdersUseCase")
	ret0, _ := ret[0].(port.UseCase[vo.UserID, []dto.OrderOutput])
	return ret0
}

// ListOrdersUseCase indicates an expected call of ListOrdersUseCase.
func (mr *MockUseCaseFactoryMockRecorder) ListOrdersUseCase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrdersUseCase", reflect.TypeOf((*MockUseCaseFactory)(nil).ListOrdersUseCase))
}

// ListWithdrawalsUseCase mocks base method.
func (m *MockUseCaseFactory) ListWithdrawalsUseCase() port.UseCase[vo.UserID, []dto.WithdrawalOutput] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWithdrawalsUseCase")
	ret0, _ := ret[0].(port.UseCase[vo.UserID, []dto.WithdrawalOutput])
	return ret0
}

// ListWithdrawalsUseCase indicates an expected call of ListWithdrawalsUseCase.
func (mr *MockUseCaseFactoryMockRecorder) ListWithdrawalsUseCase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWithdrawalsUseCase", reflect.TypeOf((*MockUseCaseFactory)(nil).ListWithdrawalsUseCase))
}

// LoginUseCase mocks base method.
func (m *MockUseCaseFactory) LoginUseCase() port.UseCase[dto.LoginInput, vo.UserID] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginUseCase")
	ret0, _ := ret[0].(port.UseCase[dto.LoginInput, vo.UserID])
	return ret0
}

// LoginUseCase indicates an expected call of LoginUseCase.
func (mr *MockUseCaseFactoryMockRecorder) LoginUseCase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginUseCase", reflect.TypeOf((*MockUseCaseFactory)(nil).LoginUseCase))
}

// ProcessAccrualUseCase mocks base method.
func (m *MockUseCaseFactory) ProcessAccrualUseCase() port.BackgroundRunner {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessAccrualUseCase")
	ret0, _ := ret[0].(port.BackgroundRunner)
	return ret0
}

// ProcessAccrualUseCase indicates an expected call of ProcessAccrualUseCase.
func (mr *MockUseCaseFactoryMockRecorder) ProcessAccrualUseCase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessAccrualUseCase", reflect.TypeOf((*MockUseCaseFactory)(nil).ProcessAccrualUseCase))
}

// RegisterUseCase mocks base method.
func (m *MockUseCaseFactory) RegisterUseCase() port.UseCase[dto.RegisterInput, vo.UserID] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterUseCase")
	ret0, _ := ret[0].(port.UseCase[dto.RegisterInput, vo.UserID])
	return ret0
}

// RegisterUseCase indicates an expected call of RegisterUseCase.
func (mr *MockUseCaseFactoryMockRecorder) RegisterUseCase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUseCase", reflect.TypeOf((*MockUseCaseFactory)(nil).RegisterUseCase))
}

// UploadOrderUseCase mocks base method.
func (m *MockUseCaseFactory) UploadOrderUseCase() port.UseCase[dto.UploadOrderInput, struct{}] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadOrderUseCase")
	ret0, _ := ret[0].(port.UseCase[dto.UploadOrderInput, struct{}])
	return ret0
}

// UploadOrderUseCase indicates an expected call of UploadOrderUseCase.
func (mr *MockUseCaseFactoryMockRecorder) UploadOrderUseCase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadOrderUseCase", reflect.TypeOf((*MockUseCaseFactory)(nil).UploadOrderUseCase))
}

// WithdrawUseCase mocks base method.
func (m *MockUseCaseFactory) WithdrawUseCase() port.UseCase[dto.WithdrawInput, struct{}] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithdrawUseCase")
	ret0, _ := ret[0].(port.UseCase[dto.WithdrawInput, struct{}])
	return ret0
}

// WithdrawUseCase indicates an expected call of WithdrawUseCase.
func (mr *MockUseCaseFactoryMockRecorder) WithdrawUseCase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithdrawUseCase", reflect.TypeOf((*MockUseCaseFactory)(nil).WithdrawUseCase))
}
