// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package converter

import (
	convext "gophermart/internal/gophermart/modules/identity/adapters/repository/postgres/converter/convext"
	model "gophermart/internal/gophermart/modules/identity/adapters/repository/postgres/model"
	entity "gophermart/internal/gophermart/modules/identity/domain/entity"
	vo "gophermart/internal/gophermart/modules/identity/domain/vo"
)

type UserConverterImpl struct{}

func (c *UserConverterImpl) ToEntity(source model.User) entity.User {
	var entityUser entity.User
	entityUser.ID = vo.UserID(source.ID)
	entityUser.Login = source.Login
	entityUser.PasswordHash = source.PasswordHash
	entityUser.CreatedAt = convext.CopyTime(source.CreatedAt)
	entityUser.UpdatedAt = convext.CopyTime(source.UpdatedAt)
	return entityUser
}
func (c *UserConverterImpl) ToModel(source entity.User) model.User {
	var modelUser model.User
	modelUser.ID = int64(source.ID)
	modelUser.Login = source.Login
	modelUser.PasswordHash = source.PasswordHash
	modelUser.CreatedAt = convext.CopyTime(source.CreatedAt)
	modelUser.UpdatedAt = convext.CopyTime(source.UpdatedAt)
	return modelUser
}
