// Code generated by MockGen. DO NOT EDIT.
// Source: internal/gophermart/domain/vo/order_number_validator.go
//
// Generated by this command:
//
//	mockgen -source=internal/gophermart/domain/vo/order_number_validator.go -destination=internal/gophermart/domain/vo/mocks/mock_order_number_validator.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOrderNumberValidator is a mock of OrderNumberValidator interface.
type MockOrderNumberValidator struct {
	ctrl     *gomock.Controller
	recorder *MockOrderNumberValidatorMockRecorder
	isgomock struct{}
}

// MockOrderNumberValidatorMockRecorder is the mock recorder for MockOrderNumberValidator.
type MockOrderNumberValidatorMockRecorder struct {
	mock *MockOrderNumberValidator
}

// NewMockOrderNumberValidator creates a new mock instance.
func NewMockOrderNumberValidator(ctrl *gomock.Controller) *MockOrderNumberValidator {
	mock := &MockOrderNumberValidator{ctrl: ctrl}
	mock.recorder = &MockOrderNumberValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderNumberValidator) EXPECT() *MockOrderNumberValidatorMockRecorder {
	return m.recorder
}

// Valid mocks base method.
func (m *MockOrderNumberValidator) Valid(s string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Valid", s)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Valid indicates an expected call of Valid.
func (mr *MockOrderNumberValidatorMockRecorder) Valid(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Valid", reflect.TypeOf((*MockOrderNumberValidator)(nil).Valid), s)
}
