// Code generated by MockGen. DO NOT EDIT.
// Source: internal/gophermart/application/port/withdrawal_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/gophermart/application/port/withdrawal_repository.go -destination=internal/gophermart/application/port/mocks/mock_withdrawal_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	entity "gophermart/internal/gophermart/domain/entity"
	vo "gophermart/internal/gophermart/domain/vo"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWithdrawalReader is a mock of WithdrawalReader interface.
type MockWithdrawalReader struct {
	ctrl     *gomock.Controller
	recorder *MockWithdrawalReaderMockRecorder
	isgomock struct{}
}

// MockWithdrawalReaderMockRecorder is the mock recorder for MockWithdrawalReader.
type MockWithdrawalReaderMockRecorder struct {
	mock *MockWithdrawalReader
}

// NewMockWithdrawalReader creates a new mock instance.
func NewMockWithdrawalReader(ctrl *gomock.Controller) *MockWithdrawalReader {
	mock := &MockWithdrawalReader{ctrl: ctrl}
	mock.recorder = &MockWithdrawalReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWithdrawalReader) EXPECT() *MockWithdrawalReaderMockRecorder {
	return m.recorder
}

// ListByUserID mocks base method.
func (m *MockWithdrawalReader) ListByUserID(ctx context.Context, userID vo.UserID) ([]entity.Withdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", ctx, userID)
	ret0, _ := ret[0].([]entity.Withdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockWithdrawalReaderMockRecorder) ListByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockWithdrawalReader)(nil).ListByUserID), ctx, userID)
}

// MockWithdrawalWriter is a mock of WithdrawalWriter interface.
type MockWithdrawalWriter struct {
	ctrl     *gomock.Controller
	recorder *MockWithdrawalWriterMockRecorder
	isgomock struct{}
}

// MockWithdrawalWriterMockRecorder is the mock recorder for MockWithdrawalWriter.
type MockWithdrawalWriterMockRecorder struct {
	mock *MockWithdrawalWriter
}

// NewMockWithdrawalWriter creates a new mock instance.
func NewMockWithdrawalWriter(ctrl *gomock.Controller) *MockWithdrawalWriter {
	mock := &MockWithdrawalWriter{ctrl: ctrl}
	mock.recorder = &MockWithdrawalWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWithdrawalWriter) EXPECT() *MockWithdrawalWriterMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockWithdrawalWriter) Create(ctx context.Context, w *entity.Withdrawal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, w)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockWithdrawalWriterMockRecorder) Create(ctx, w any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWithdrawalWriter)(nil).Create), ctx, w)
}

// MockWithdrawalRepository is a mock of WithdrawalRepository interface.
type MockWithdrawalRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWithdrawalRepositoryMockRecorder
	isgomock struct{}
}

// MockWithdrawalRepositoryMockRecorder is the mock recorder for MockWithdrawalRepository.
type MockWithdrawalRepositoryMockRecorder struct {
	mock *MockWithdrawalRepository
}

// NewMockWithdrawalRepository creates a new mock instance.
func NewMockWithdrawalRepository(ctrl *gomock.Controller) *MockWithdrawalRepository {
	mock := &MockWithdrawalRepository{ctrl: ctrl}
	mock.recorder = &MockWithdrawalRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWithdrawalRepository) EXPECT() *MockWithdrawalRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockWithdrawalRepository) Create(ctx context.Context, w *entity.Withdrawal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, w)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockWithdrawalRepositoryMockRecorder) Create(ctx, w any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWithdrawalRepository)(nil).Create), ctx, w)
}

// ListByUserID mocks base method.
func (m *MockWithdrawalRepository) ListByUserID(ctx context.Context, userID vo.UserID) ([]entity.Withdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", ctx, userID)
	ret0, _ := ret[0].([]entity.Withdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockWithdrawalRepositoryMockRecorder) ListByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockWithdrawalRepository)(nil).ListByUserID), ctx, userID)
}
