// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonBed2650eDecodeGophermartInternalGophermartPresentationHttpDto(in *jlexer.Lexer, out *WithdrawRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "order":
			out.Order = string(in.String())
		case "sum":
			out.Sum = float64(in.Float64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBed2650eEncodeGophermartInternalGophermartPresentationHttpDto(out *jwriter.Writer, in WithdrawRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"order\":"
		out.RawString(prefix[1:])
		out.String(string(in.Order))
	}
	{
		const prefix string = ",\"sum\":"
		out.RawString(prefix)
		out.Float64(float64(in.Sum))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v WithdrawRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonBed2650eEncodeGophermartInternalGophermartPresentationHttpDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WithdrawRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonBed2650eEncodeGophermartInternalGophermartPresentationHttpDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WithdrawRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonBed2650eDecodeGophermartInternalGophermartPresentationHttpDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WithdrawRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonBed2650eDecodeGophermartInternalGophermartPresentationHttpDto(l, v)
}
func easyjsonBed2650eDecodeGophermartInternalGophermartPresentationHttpDto1(in *jlexer.Lexer, out *BalanceResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "current":
			out.Current = float64(in.Float64())
		case "withdrawn":
			out.Withdrawn = float64(in.Float64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBed2650eEncodeGophermartInternalGophermartPresentationHttpDto1(out *jwriter.Writer, in BalanceResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"current\":"
		out.RawString(prefix[1:])
		out.Float64(float64(in.Current))
	}
	{
		const prefix string = ",\"withdrawn\":"
		out.RawString(prefix)
		out.Float64(float64(in.Withdrawn))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BalanceResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonBed2650eEncodeGophermartInternalGophermartPresentationHttpDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BalanceResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonBed2650eEncodeGophermartInternalGophermartPresentationHttpDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BalanceResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonBed2650eDecodeGophermartInternalGophermartPresentationHttpDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BalanceResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonBed2650eDecodeGophermartInternalGophermartPresentationHttpDto1(l, v)
}
