// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package converter

import (
	convext "gophermart/internal/gophermart/adapters/repository/postgres/converter/convext"
	model "gophermart/internal/gophermart/adapters/repository/postgres/model"
	entity "gophermart/internal/gophermart/domain/entity"
	vo "gophermart/internal/gophermart/domain/vo"
)

type BalanceAccountConverterImpl struct{}

func (c *BalanceAccountConverterImpl) ToEntity(source model.BalanceAccount) entity.BalanceAccount {
	var entityBalanceAccount entity.BalanceAccount
	entityBalanceAccount.UserID = vo.UserID(source.UserID)
	entityBalanceAccount.Current = vo.Points(source.Current)
	entityBalanceAccount.WithdrawnTotal = vo.Points(source.WithdrawnTotal)
	entityBalanceAccount.CreatedAt = convext.CopyTime(source.CreatedAt)
	entityBalanceAccount.UpdatedAt = convext.CopyTime(source.UpdatedAt)
	entityBalanceAccount.Version = source.Version
	return entityBalanceAccount
}
func (c *BalanceAccountConverterImpl) ToModel(source entity.BalanceAccount) model.BalanceAccount {
	var modelBalanceAccount model.BalanceAccount
	modelBalanceAccount.UserID = int64(source.UserID)
	modelBalanceAccount.Current = c.voPointsToFloat64(source.Current)
	modelBalanceAccount.WithdrawnTotal = c.voPointsToFloat64(source.WithdrawnTotal)
	modelBalanceAccount.CreatedAt = convext.CopyTime(source.CreatedAt)
	modelBalanceAccount.UpdatedAt = convext.CopyTime(source.UpdatedAt)
	modelBalanceAccount.Version = source.Version
	return modelBalanceAccount
}
func (c *BalanceAccountConverterImpl) voPointsToFloat64(source vo.Points) float64 {
	return float64(source)
}
