// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package converter

import (
	convext "gophermart/internal/gophermart/adapters/repository/postgres/converter/convext"
	model "gophermart/internal/gophermart/adapters/repository/postgres/model"
	entity "gophermart/internal/gophermart/domain/entity"
	vo "gophermart/internal/gophermart/domain/vo"
)

type OrderConverterImpl struct{}

func (c *OrderConverterImpl) ToEntity(source model.Order) (entity.Order, error) {
	var entityOrder entity.Order
	entityOrder.Number = vo.OrderNumber(source.Number)
	entityOrder.UserID = vo.UserID(source.UserID)
	entityOrderStatus, err := convext.StatusFromDB(source.Status)
	if err != nil {
		return entityOrder, err
	}
	entityOrder.Status = entityOrderStatus
	entityOrder.Accrual = convext.PointsFromDB(source.Accrual)
	entityOrder.UploadedAt = convext.CopyTime(source.UploadedAt)
	entityOrder.ProcessedAt = convext.CopyTimePtr(source.ProcessedAt)
	return entityOrder, nil
}
func (c *OrderConverterImpl) ToModel(source entity.Order) (model.Order, error) {
	var modelOrder model.Order
	modelOrder.Number = vo.OrderNumber(source.Number)
	modelOrder.UserID = vo.UserID(source.UserID)
	xint16, err := convext.StatusToDB(source.Status)
	if err != nil {
		return modelOrder, err
	}
	modelOrder.Status = xint16
	modelOrder.Accrual = convext.PointsToDB(source.Accrual)
	modelOrder.UploadedAt = convext.CopyTime(source.UploadedAt)
	modelOrder.ProcessedAt = convext.CopyTimePtr(source.ProcessedAt)
	return modelOrder, nil
}
