// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package converter

import (
	convext "gophermart/internal/gophermart/adapters/repository/postgres/converter/convext"
	model "gophermart/internal/gophermart/adapters/repository/postgres/model"
	entity "gophermart/internal/gophermart/domain/entity"
	vo "gophermart/internal/gophermart/domain/vo"
)

type WithdrawalConverterImpl struct{}

func (c *WithdrawalConverterImpl) ToEntity(source model.Withdrawal) entity.Withdrawal {
	var entityWithdrawal entity.Withdrawal
	entityWithdrawal.UserID = vo.UserID(source.UserID)
	entityWithdrawal.OrderNumber = vo.OrderNumber(source.OrderNumber)
	entityWithdrawal.Amount = vo.Points(source.Amount)
	entityWithdrawal.ProcessedAt = convext.CopyTime(source.ProcessedAt)
	return entityWithdrawal
}
func (c *WithdrawalConverterImpl) ToModel(source entity.Withdrawal) model.Withdrawal {
	var modelWithdrawal model.Withdrawal
	modelWithdrawal.UserID = int64(source.UserID)
	modelWithdrawal.OrderNumber = string(source.OrderNumber)
	modelWithdrawal.Amount = float64(source.Amount)
	modelWithdrawal.ProcessedAt = convext.CopyTime(source.ProcessedAt)
	return modelWithdrawal
}
