// Code generated by MockGen. DO NOT EDIT.
// Source: internal/gophermart/application/port/balance_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/gophermart/application/port/balance_repository.go -destination=internal/gophermart/application/port/mocks/mock_balance_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	entity "gophermart/internal/gophermart/domain/entity"
	vo "gophermart/internal/gophermart/domain/vo"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBalanceAccountReader is a mock of BalanceAccountReader interface.
type MockBalanceAccountReader struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceAccountReaderMockRecorder
	isgomock struct{}
}

// MockBalanceAccountReaderMockRecorder is the mock recorder for MockBalanceAccountReader.
type MockBalanceAccountReaderMockRecorder struct {
	mock *MockBalanceAccountReader
}

// NewMockBalanceAccountReader creates a new mock instance.
func NewMockBalanceAccountReader(ctrl *gomock.Controller) *MockBalanceAccountReader {
	mock := &MockBalanceAccountReader{ctrl: ctrl}
	mock.recorder = &MockBalanceAccountReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceAccountReader) EXPECT() *MockBalanceAccountReaderMockRecorder {
	return m.recorder
}

// FindByUserID mocks base method.
func (m *MockBalanceAccountReader) FindByUserID(ctx context.Context, userID vo.UserID) (*entity.BalanceAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", ctx, userID)
	ret0, _ := ret[0].(*entity.BalanceAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockBalanceAccountReaderMockRecorder) FindByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockBalanceAccountReader)(nil).FindByUserID), ctx, userID)
}

// MockBalanceAccountWriter is a mock of BalanceAccountWriter interface.
type MockBalanceAccountWriter struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceAccountWriterMockRecorder
	isgomock struct{}
}

// MockBalanceAccountWriterMockRecorder is the mock recorder for MockBalanceAccountWriter.
type MockBalanceAccountWriterMockRecorder struct {
	mock *MockBalanceAccountWriter
}

// NewMockBalanceAccountWriter creates a new mock instance.
func NewMockBalanceAccountWriter(ctrl *gomock.Controller) *MockBalanceAccountWriter {
	mock := &MockBalanceAccountWriter{ctrl: ctrl}
	mock.recorder = &MockBalanceAccountWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceAccountWriter) EXPECT() *MockBalanceAccountWriterMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBalanceAccountWriter) Create(ctx context.Context, acc *entity.BalanceAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, acc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBalanceAccountWriterMockRecorder) Create(ctx, acc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBalanceAccountWriter)(nil).Create), ctx, acc)
}

// Update mocks base method.
func (m *MockBalanceAccountWriter) Update(ctx context.Context, acc *entity.BalanceAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, acc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockBalanceAccountWriterMockRecorder) Update(ctx, acc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBalanceAccountWriter)(nil).Update), ctx, acc)
}

// MockBalanceAccountRepository is a mock of BalanceAccountRepository interface.
type MockBalanceAccountRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceAccountRepositoryMockRecorder
	isgomock struct{}
}

// MockBalanceAccountRepositoryMockRecorder is the mock recorder for MockBalanceAccountRepository.
type MockBalanceAccountRepositoryMockRecorder struct {
	mock *MockBalanceAccountRepository
}

// NewMockBalanceAccountRepository creates a new mock instance.
func NewMockBalanceAccountRepository(ctrl *gomock.Controller) *MockBalanceAccountRepository {
	mock := &MockBalanceAccountRepository{ctrl: ctrl}
	mock.recorder = &MockBalanceAccountRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceAccountRepository) EXPECT() *MockBalanceAccountRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBalanceAccountRepository) Create(ctx context.Context, acc *entity.BalanceAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, acc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBalanceAccountRepositoryMockRecorder) Create(ctx, acc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBalanceAccountRepository)(nil).Create), ctx, acc)
}

// FindByUserID mocks base method.
func (m *MockBalanceAccountRepository) FindByUserID(ctx context.Context, userID vo.UserID) (*entity.BalanceAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", ctx, userID)
	ret0, _ := ret[0].(*entity.BalanceAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockBalanceAccountRepositoryMockRecorder) FindByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockBalanceAccountRepository)(nil).FindByUserID), ctx, userID)
}

// Update mocks base method.
func (m *MockBalanceAccountRepository) Update(ctx context.Context, acc *entity.BalanceAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, acc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockBalanceAccountRepositoryMockRecorder) Update(ctx, acc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBalanceAccountRepository)(nil).Update), ctx, acc)
}
