// Code generated by MockGen. DO NOT EDIT.
// Source: internal/gophermart/application/port/token_provider.go
//
// Generated by this command:
//
//	mockgen -source=internal/gophermart/application/port/token_provider.go -destination=internal/gophermart/application/port/mocks/mock_token_provider.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	vo "gophermart/internal/gophermart/domain/vo"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTokenProvider is a mock of TokenProvider interface.
type MockTokenProvider struct {
	ctrl     *gomock.Controller
	recorder *MockTokenProviderMockRecorder
	isgomock struct{}
}

// MockTokenProviderMockRecorder is the mock recorder for MockTokenProvider.
type MockTokenProviderMockRecorder struct {
	mock *MockTokenProvider
}

// NewMockTokenProvider creates a new mock instance.
func NewMockTokenProvider(ctrl *gomock.Controller) *MockTokenProvider {
	mock := &MockTokenProvider{ctrl: ctrl}
	mock.recorder = &MockTokenProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenProvider) EXPECT() *MockTokenProviderMockRecorder {
	return m.recorder
}

// Issue mocks base method.
func (m *MockTokenProvider) Issue(userID vo.UserID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Issue", userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Issue indicates an expected call of Issue.
func (mr *MockTokenProviderMockRecorder) Issue(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Issue", reflect.TypeOf((*MockTokenProvider)(nil).Issue), userID)
}

// Validate mocks base method.
func (m *MockTokenProvider) Validate(token string) (vo.UserID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", token)
	ret0, _ := ret[0].(vo.UserID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Validate indicates an expected call of Validate.
func (mr *MockTokenProviderMockRecorder) Validate(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockTokenProvider)(nil).Validate), token)
}
